cf-cli/cf-cli_6.25.0_linux_x86-64.tgz:
  size: 5088758
  object_id: 4316161b-3625-4eb3-97a7-6631de9360f2
  sha: 82728ff9fed87554a14a2e5d2b4b743b8f2885ae
cf-kibana/kibana-5.6.13-linux-x86_64.tar.gz:
  size: 53161803
  object_id: 69d51cbc-ab69-4f87-4edf-beb063fd8e91
  sha: 5562635acea8b262dc47e2c09f25572e30cef950
redis/redis-3.2.9.tar.gz:
  size: 1547695
  object_id: a1230536-4203-40b9-97e1-9f11d470308d
  sha: 8fad759f28bcb14b94254124d824f1f3ed7b6aa6
ruby-2.3/bundler-1.11.2.gem:
  size: 263168
  object_id: 49f1cda1-4099-445a-afce-1542e0ddfe74
  sha: 8eb956dec72da753d3d2a2126c78508b17af434e
ruby-2.3/rake-11.2.2.gem:
  size: 102400
  object_id: dccd98c7-85ee-4663-bb63-2346801763dc
  sha: 879e7c02b1a0b37333a91f11621f798deb874b6e
ruby-2.3/ruby-2.3.1.tar.gz:
  size: 17797997
  object_id: 6f94d256-a798-4864-bd74-fef4bcef32cf
  sha: c39b4001f7acb4e334cb60a0f4df72d434bef711
ruby-2.3/rubygems-2.6.4.tgz:
  size: 478582
  object_id: 40690581-ce13-473c-9cc5-3a459e67be3b
  sha: 8ef39e536af2ecd20b0e7a95765fa6a485087ac8
