---
ruby-2.3/bundler-1.11.2.gem:
  object_id: 49f1cda1-4099-445a-afce-1542e0ddfe74
  sha: 8eb956dec72da753d3d2a2126c78508b17af434e
  size: 263168
ruby-2.3/rake-11.2.2.gem:
  object_id: dccd98c7-85ee-4663-bb63-2346801763dc
  sha: 879e7c02b1a0b37333a91f11621f798deb874b6e
  size: 102400
ruby-2.3/ruby-2.3.1.tar.gz:
  object_id: 6f94d256-a798-4864-bd74-fef4bcef32cf
  sha: c39b4001f7acb4e334cb60a0f4df72d434bef711
  size: 17797997
ruby-2.3/rubygems-2.6.4.tgz:
  object_id: 40690581-ce13-473c-9cc5-3a459e67be3b
  sha: 8ef39e536af2ecd20b0e7a95765fa6a485087ac8
  size: 478582
golang/go1.7.5.linux-amd64.tar.gz:
  object_id: 0c5b5c61-90f1-4432-9aa1-dd426c9fa7d4
  sha: 7c6902ce8cd3b9963082d748c50df074e4896796
  size: 84176916
cf-cli/cf-cli_6.25.0_linux_x86-64.tgz:
  object_id: 4316161b-3625-4eb3-97a7-6631de9360f2
  sha: 82728ff9fed87554a14a2e5d2b4b743b8f2885ae
  size: 5088758
cf-kibana/kibana-5.3.2-linux-x86_64.tar.gz:
  object_id: b9a78107-5765-4ab5-97d3-b788c18821fc
  sha: 003cec9da459cec0bb0feffd6859aa47fbe72795
  size: 38743345
